// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PremiseService.Infrastructure.Persistence;

#nullable disable

namespace PremiseService.Infrastructure.Migrations
{
    [DbContext(typeof(PremiseDbContext))]
    [Migration("20260224201851_MakeGoalAndStrategyOptionalAndVersioning")]
    partial class MakeGoalAndStrategyOptionalAndVersioning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PremiseService.Domain.Entities.Premise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("NewVersionOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_version_of_id");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("ix_premises_goal_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_premises_is_active");

                    b.HasIndex("NewVersionOfId")
                        .IsUnique()
                        .HasDatabaseName("ix_premises_new_version_of_id");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("ix_premises_strategy_id");

                    b.ToTable("premises", (string)null);
                });

            modelBuilder.Entity("PremiseService.Domain.Entities.Premise", b =>
                {
                    b.HasOne("PremiseService.Domain.Entities.Premise", "NewVersionOf")
                        .WithOne("NewerVersion")
                        .HasForeignKey("PremiseService.Domain.Entities.Premise", "NewVersionOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NewVersionOf");
                });

            modelBuilder.Entity("PremiseService.Domain.Entities.Premise", b =>
                {
                    b.Navigation("NewerVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
