{
 "title": "ASP.NET Core Application Metrics",
 "tags": [
  "aspnetcore",
  "opentelemetry",
  "dotnet"
 ],
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(http_server_request_duration_seconds_count, job)"
   },
   {
    "name": "instance",
    "query": "label_values(http_server_request_duration_seconds_count{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance)(rate(http_server_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} request rate"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_request_duration_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[5m])) / sum by (instance) (rate(http_server_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\"}[5m])) * 1000",
     "legendFormat": "{{instance}} average latency (ms)"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Working Set Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Working Set"
    }
   ]
  }
 ]
}