// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrchestrationService.Infrastructure.Persistence;

#nullable disable

namespace OrchestrationService.Infrastructure.Migrations
{
    [DbContext(typeof(OrchestrationDbContext))]
    [Migration("20260305000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrchestrationService.Domain.Entities.SagaStep", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime?>("CompensatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CompensationEndpoint").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("CompensationPayload").IsRequired().HasMaxLength(5000).HasColumnType("character varying(5000)");
                b.Property<DateTime>("ExecutedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("SagaWorkflowId").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<string>("StepName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.HasIndex("SagaWorkflowId");
                b.ToTable("SagaSteps");
            });

            modelBuilder.Entity("OrchestrationService.Domain.Entities.SagaWorkflow", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CurrentStep").IsRequired().HasColumnType("text");
                b.Property<Guid>("GoalId").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("GoalId").IsUnique();
                b.ToTable("SagaWorkflows");
            });

            modelBuilder.Entity("OrchestrationService.Domain.Entities.SagaStep", b =>
            {
                b.HasOne("OrchestrationService.Domain.Entities.SagaWorkflow", "Workflow")
                    .WithMany("Steps")
                    .HasForeignKey("SagaWorkflowId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Workflow");
            });

            modelBuilder.Entity("OrchestrationService.Domain.Entities.SagaWorkflow", b =>
            {
                b.Navigation("Steps");
            });
#pragma warning restore 612, 618
        }
    }
}
